### ISSUE TITLE
Distributing my fork to central repo with a different groupId

### ISSUE THREAD

**Issue by peter-fu** [dohque/redis-runner#1]
Hi @dohque ,

It's been a while since we connected last time. Hope you're doing well.

Thanks again for open sourcing this project and the permission for me to make the distribution to OSChina, we've been using it for years. Unfortunately OSChina Maven was stopped last year, and I decided to make one step forward to proceed the distribution of this project to central repo.

I am making a distribution to central repo of redis-runner of [my fork](https://github.com/kernelogic/redis-runner). The [project request](https://issues.sonatype.org/browse/OSSRH-23954) has been approved. However, I am only allowed to make the distribution under my own groupId which is "com.kernelogic".

And I am planning to apply Apache License 2.

Does that sound OK by you?

PS: At the meanwhile I'm also proceeding the open sourcing of [play-redis](https://bitbucket.org/kernelogicinc/play-redis) library. It's already made public access, the distribution to central repo hasn't been made yet.

Best Regards,
Peter

**Comment by dohque** [comment]
Hi Peter

Is it hard to make distribution to maven central? I was not expecting
anybody is using redis-runner.
I switched to use my other library jedis-mock(
https://github.com/dohque/jedis-mock ) which enabling mocking of redis
access library we used and compatible with spring. Then I stopped working
in that firm
and moved to US.

I'm not agree about license. I would prefer to put it under MIT or BSD
license.
And It would great to join effort in putting it to maven central.
I have this on my todo for years. Now I have some time to help with this.

Regards.
Ruslan Pilin.

Skype: dohque

**Comment by peter-fu** [comment]
Nice.

I followed this guide to proceed the distribution to central repo, it does take some steps.
http://central.sonatype.org/pages/ossrh-guide.html

And code changes here.
https://github.com/kernelogic/redis-runner/tree/central-repo

No formal release has been made by me yet. I will remove the snapshot release I made the other day.

Let's close this issue, too.

Thanks,
Peter

**Comment by peter-fu** [comment]
I removed the snapshot release from https://oss.sonatype.org/content/repositories/snapshots/com/kernelogic/ru/pilin/redis/runner/redis-runner/0.0.3-SNAPSHOT/.
